# Generated by Django 4.0.5 on 2022-06-27 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0002_batteries_serial_batteries_state_of_charge_and_more'),
        ('stations', '0002_stations_contact_stations_latitude_and_more'),
        ('drivers', '0002_drivers_contact_drivers_emoto_license_and_more'),
        ('swaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaps',
            name='amount_payable',
            field=models.DecimalField(decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='swaps',
            name='battery_swapped_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='battery_swapped_in', to='batteries.batteries'),
        ),
        migrations.AddField(
            model_name='swaps',
            name='battery_swapped_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='battery_swapped_out', to='batteries.batteries'),
        ),
        migrations.AddField(
            model_name='swaps',
            name='charge_used',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='swaps',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to='drivers.drivers'),
        ),
        migrations.AddField(
            model_name='swaps',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='station', to='stations.stations'),
        ),
        migrations.AddField(
            model_name='swaps',
            name='status',
            field=models.CharField(choices=[('INPROGRESSD', 'INPROGRESS'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
    ]
