# Generated by Django 4.0.5 on 2022-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0002_swaps_amount_payable_swaps_battery_swapped_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaps',
            name='status',
            field=models.CharField(choices=[('INPROGRESS', 'INPROGRESS'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
    ]
