# Generated by Django 4.0.5 on 2022-06-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0003_alter_swaps_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaps',
            name='distance_traveled',
            field=models.DecimalField(decimal_places=2, max_digits=25, null=True),
        ),
    ]
