# Generated by Django 4.0.5 on 2022-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0002_batteries_serial_batteries_state_of_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batteries',
            name='gross_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='batteries',
            name='net_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='batterytelematics',
            name='external_temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
