# Generated by Django 4.0.5 on 2022-06-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0003_batteries_gross_capacity_batteries_net_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batteries',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='batterytelematics',
            options={'ordering': ['-created_at']},
        ),
    ]
